/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 charminar.glb 
Author: Dolores (https://sketchfab.com/upto21)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/charminar-hyderabad-82603f1fe3ed4c31b37786e2bc2b63b0
Title: Charminar, Hyderabad
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CharminarTry(props) {
  const { nodes, materials } = useGLTF("/charminar.glb");
  return (
    <group {...props} dispose={null} scale={5} position-y={-6.5} position-z={8}>
      <pointLight
        intensity={0.5}
        position-y={1}
        position-z={-5}
        position-x={-3}
      />
      <pointLight
        intensity={0.5}
        position-y={1}
        position-z={2}
        position-x={-3}
      />
      <pointLight
        intensity={0.5}
        position-y={1}
        position-z={2}
        position-x={4}
      />
      <pointLight
        intensity={0.5}
        position-y={1}
        position-z={-5}
        position-x={4}
      />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-0.965, 2.747, 1.252]}
          rotation={[0, 0, -1.178]}
          scale={0.166}
        >
          <mesh
            geometry={nodes.Circle003_0.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Circle003_0_1.geometry}
            material={materials.Material}
          />
        </group>
        <mesh
          geometry={nodes.Circle006_0.geometry}
          material={materials.Material}
          position={[0.918, 2.748, 3.808]}
          rotation={[0, 0, -2.749]}
          scale={0.166}
        />
        <mesh
          geometry={nodes.Cube_0.geometry}
          material={materials["Material.001"]}
          position={[-0.047, 1.831, -0.242]}
          scale={[1.643, 1.643, 0.327]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/charminar.glb");
