/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Delhi.glb 
*/

import React, { useRef } from "react";
import { Decal, PositionalAudio, useGLTF, useTexture } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
// import { Charminar } from "./Charminar";
// import { CharminarTry } from "./Charminartry";
// import { CharminarNew } from "./CharminarNew";
import { IndiaGateTry2 } from "./IndiaGateTry2";
import { MOUSE } from "three";
import { useEffect } from "react";
import { useState } from "react";

const Delhi = (props) => {
  const { nodes, materials } = useGLTF("/Delhi.glb");
  const v1 = [
    "./Photos/Haryana/Dance/dhdance1.jpg",
    "./Photos/Haryana/Dance/dhdance2.jpg",
    "./Photos/Haryana/Dance/dhdance3.jpg",
    "./Photos/Haryana/Dance/dhdance4.jpg",
  ];

  const v2 = [
    "./Photos/Haryana/festivals/dhfest1.jpg",
    "./Photos/Haryana/festivals/dhfest2.jpg",
    "./Photos/Haryana/festivals/dhfest3.jpg",
    "./Photos/Haryana/festivals/dhfest4.jpg",
  ];

  const v3 = [
    "./Photos/Haryana/Food/dhfood1.jpg",
    "./Photos/Haryana/Food/dhfood2.jpg",
    "./Photos/Haryana/Food/dhfood3.jpg",
    "./Photos/Haryana/Food/dhfood4.jpg",
  ];

  const v4 = [
    "./Photos/Haryana/Temple/dhtemple1.jpg",
    "./Photos/Haryana/Temple/dhtemple2.jpg",
    "./Photos/Haryana/Temple/dhtemple3.jpg",
    "./Photos/Haryana/Temple/dhtemple4.jpg",
  ];

  const [currentIndex, setCurrentIndex] = useState(0);

  //  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentIndex((prevIndex) => (prevIndex + 1) % v1.length);
    }, 3000);

    return () => clearInterval(intervalId);
  }, []);

  const texture = useTexture(v1[currentIndex]);
  const texture1 = useTexture(v2[currentIndex]);
  const texture2 = useTexture(v3[currentIndex]);
  const texture3 = useTexture(v4[currentIndex]);
  // console.log("dummy");
  return (
    // <Canvas
    //   style={{
    //     width: "100%",
    //     height: "100%",
    //     position: "fixed",
    //     top: 0,
    //     left: 0,
    //     overflow: "hidden",
    //   }}
    //   camera={{ position: [-20, 0, 0] }}
    // >
    <>
      <PositionalAudio autoplay loop url="/Delhi.mp3" distance={2} />
      <OrbitControls
        enablePan={true}
        enableRotate={true}
        autoRotate={true}
        panSpeed={0.5}
        autoRotateSpeed={1}
        maxDistance={18}
        mouseButtons={{
          LEFT: MOUSE.LEFT,
          UP: MOUSE.UP,
          RIGHT: MOUSE.RIGHT,
          BOTTOM: MOUSE.BOTTOM,
        }}
      />
      <ambientLight intensity={0.5} />
      <group {...props} dispose={null}>
        <PositionalAudio autoplay loop url="/Delhi.mp3" distance={1} />
        <IndiaGateTry2 />
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[20, 0, 0]}
          rotation-x={Math.PI}
          scale={20}
        />

        {/* <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Material.001"]}
          position={[20, 0, 0]}
          rotation-x={Math.PI}
          scale={20}

/> */}
        <mesh scale={41} position={[3, 10, 20]} rotation-y={1 * Math.PI}>
          <planeGeometry />
          <meshBasicMaterial />
          <Decal
            position={[0, 0, 0]} // Position of the decal
            rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
            scale={1} // Scale of the decal
          >
            <meshBasicMaterial map={texture1} />
          </Decal>
        </mesh>

        {/* <mesh
          geometry={nodes.Cube003.geometry}
          material={materials["Material.002"]}
          position={[20, 0, 0]}
          rotation-x={Math.PI}
          scale={20}
        > */}
        <mesh scale={41} position={[3, 10, -20]}>
          <planeGeometry />
          <meshBasicMaterial />
          <Decal
            // Makes "bounding box" of the decal visible
            position={[0, 0, 0]} // Position of the decal
            rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
            scale={1} // Scale of the decal
            // The mesh should take precedence over the original
          >
            <meshBasicMaterial
              // scale={5}
              map={texture}
              // polygonOffset
              // polygonOffsetFactor={-1}
            />
          </Decal>
        </mesh>

        {/* <mesh
          geometry={nodes.Cube004.geometry}
          material={materials["Material.003"]}
          position={[20, 0, 0]}
          rotation-x={Math.PI}
          scale={20}
        /> */}

        <mesh scale={41} position={[23, 10, 0]} rotation-y={1.5 * Math.PI}>
          <planeGeometry />
          <meshBasicMaterial />
          <Decal
            // Makes "bounding box" of the decal visible
            position={[0, 0, 0]} // Position of the decal
            rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
            scale={1} // Scale of the decal
            // The mesh should take precedence over the original
          >
            <meshBasicMaterial
              // scale={5}
              map={texture2}
              // polygonOffset
              // polygonOffsetFactor={-1}
            />
          </Decal>
        </mesh>

        {/* <mesh
          geometry={nodes.Cube005.geometry}
          material={materials["Material.004"]}
          position={[20, 0, 0]}
          rotation-x={Math.PI}
          scale={20}
        /> */}
        <mesh scale={41} position={[-16.5, 10, 0]} rotation-y={2.5 * Math.PI}>
          <planeGeometry />
          <meshBasicMaterial />
          <Decal
            // Makes "bounding box" of the decal visible
            position={[0, 0, 0]} // Position of the decal
            rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
            scale={1} // Scale of the decal
            // The mesh should take precedence over the original
          >
            <meshBasicMaterial
              // scale={5}
              map={texture3}
              // polygonOffset
              // polygonOffsetFactor={-1}
            />
          </Decal>
        </mesh>
      </group>
    </>
    // </Canvas>
  );
};

useGLTF.preload("/Delhi.glb");
export default Delhi;
