/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 EC.glb 
Author: GSXNet (https://sketchfab.com/gsxn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ellora-caves-india-1a5ec1e212f9451e80dc051e97164d17
Title: Ellora Caves | India
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function EC(props) {
  const { nodes, materials } = useGLTF("/EC.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={0.01}
      position-y={-7.2}
      position-z={0}
      rotation-y={4.5}
      position-x={6}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Retopo_Model_Tex_0.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Retopo_Model_Tex_0_1.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Retopo_Model_Tex_0_2.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Retopo_Model_Tex_0_3.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Retopo_Model_Tex_0_4.geometry}
          material={materials.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/EC.glb");
