/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 IndiaGateTry2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function IndiaGateTry2(props) {
  const { nodes, materials } = useGLTF("/IndiaGateTry2.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={1.25}
      position-y={-9.5}
      position-z={0}
      rotation-y={1.55}
    >
      {/* <pointLight
        intensity={0.05}
        position-y={2}
        position-z={-2}
        position-x={-8}
      /> */}
      <pointLight
        intensity={0.1}
        position-y={8}
        position-z={-2}
        position-x={-8}
      />
      <pointLight
        intensity={0.1}
        position-y={8}
        position-z={2}
        position-x={0}
      />
      <pointLight
        intensity={0.1}
        position-y={8}
        position-z={-2}
        position-x={4}
      />
      <pointLight
        intensity={0.1}
        position-y={8}
        position-z={-5}
        position-x={0}
      />
      <mesh
        geometry={nodes.IndiaGate_Mesh.geometry}
        material={materials.Material}
      />
      <mesh
        geometry={nodes.IndiaGate_Mesh_1.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/IndiaGateTry2.glb");
