/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 indianTemples.glb 
Author: yanix (https://sketchfab.com/yanix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/indian-temples-12b72dbe488f4800a080d352c724247f
Title: Indian Temples
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function IndianTemples(props) {
  const { nodes, materials } = useGLTF("/indianTemples.glb");
  return (
    <group {...props} dispose={null} scale={0.005} position-y={-10}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Cube303_Temple_03_0.geometry}
          material={materials.Temple_03}
        />
        <mesh
          geometry={nodes.Cube303_Temple_03_0_1.geometry}
          material={materials.Temple_03}
        />
        <mesh
          geometry={nodes.Cube303_Temple_03_0_2.geometry}
          material={materials.Temple_03}
        />
        <mesh
          geometry={nodes.Cube303_Temple_03_0_3.geometry}
          material={materials.Temple_03}
        />
      </group>
      <mesh
        geometry={nodes.Cube051_Temple_01_0.geometry}
        material={materials.Temple_01}
        position={[-1742.371, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Plane017_Temple_02_0.geometry}
        material={materials.Temple_02}
        position={[1856.714, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/indianTemples.glb");
