/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 TajMahal.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { AmbientLight, DirectionalLight } from "three";

export function TajMahal(props) {
  const { nodes, materials } = useGLTF("/TajMahal.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={0.15}
      position-y={-9.5}
      position-z={0}
      position-x={0}
    >
      <directionalLight intensity={10} position-y={10} position-x={-3} />
      <directionalLight intensity={10} position-y={10} position-x={7} />
      <spotLight intensity={1} position-y={-5} />
      {/* <pointLight
        intensity={0.25}
        position-y={2}
        position-z={-2}
        position-x={-8}
      />
      <pointLight
        intensity={0.25}
        position-y={0}
        position-z={2}
        position-x={0}
      />
      <pointLight
        intensity={0.25}
        position-y={0}
        position-z={-2}
        position-x={4}
      />
      <pointLight
        intensity={0.25}
        position-y={0}
        position-z={-5}
        position-x={0}
      /> */}
      <mesh
        geometry={nodes.TajMahal.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/TajMahal.glb");
